### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by aaronjensen** [sunaku/guard-tork#1]
I added a `guard 'tork'` with some of my spec files listed, it ran and started tork, but no file changes actually ran any tests as far as I could see. I was able to run tests manually via `tork-remote tork-engine`

**Comment by sunaku** [comment]
Did you add the necessary watch() statements to your `guard :tork` block?

Please run `guard init tork` to get a working example of how to configure your Guardfile.

**Comment by aaronjensen** [comment]
Ah, I did not have the event handler set up. Ok, so that works. It's not showing the log on failure or success though, but I'm guessing I could just dump the log file that it creates in my event handler? Or is there some other way? (I could open an issue for this)

**Comment by sunaku** [comment]
Yes, you could do that.

I should mention that tork-guard currently does not behave _exactly_ like tork.  I just whipped this up, with minimal defaults (exemplified in the Guardfile template), to let the user run `tork-engine` and do whatever they want thereafter.

If you want to emulate tork behavior in guard-tork, see [how tork(1) reacts to tork-engine(1) messages](https://github.com/sunaku/tork/blob/v19.0.0/lib/tork/cliapp.rb#L30-52) for reference. :neckbeard:
